MD001: false # Os níveis de cabeçalho devem ser incrementados em apenas um nível por vez
MD002: false # O primeiro cabeçalho deve ser um cabeçalho h1
MD003: false # Estilo do cabeçalho
MD004: false # Estilo de lista não ordenado
MD005: false # Recuo inconsistente para itens de lista no mesmo nível
MD006: false # Considere iniciar listas com marcadores no início da linha
MD007: false # Recuo de lista não ordenado
MD009: false # Espaços à direita
MD010: false # Tabulações rígidas
MD011: false # Sintaxe de link invertida
MD012: false # Várias linhas em branco consecutivas
MD013: false # Comprimento da linha
MD014: false # Cifrões usados antes de comandos sem mostrar a saída
MD018: false # Nenhum espaço após o hash no cabeçalho estilo atx
MD019: false # Vários espaços após o hash no cabeçalho estilo atx
MD020: false # Nenhum espaço dentro dos hashes no cabeçalho estilo atx fechado
MD021: false # Vários espaços dentro dos hashes no cabeçalho estilo atx fechado
MD022: false # Os cabeçalhos devem ser delimitados por espaços em branco Linhas
MD023: false # Os cabeçalhos devem começar no início da linha
MD024: false # Vários cabeçalhos com o mesmo conteúdo
MD025: false # Vários cabeçalhos de nível superior no mesmo documento
MD026: false # Pontuação final no cabeçalho
MD027: false # Vários espaços após o símbolo de citação
MD028: false # Linha em branco dentro de citação
MD029: false # Prefixo de item de lista ordenada
MD030: false # Espaços após marcadores de lista
MD031: false # Blocos de código delimitados devem ser delimitados por linhas em branco
MD032: false # Listas devem ser delimitadas por linhas em branco
MD033: false # HTML embutido
MD034: false # URL simples usada
MD035: false # Estilo de régua horizontal
MD036: false # Ênfase usada em vez de um cabeçalho
MD037: false # Espaços dentro de marcadores de ênfase
MD038: false # Espaços dentro de elementos de intervalo de código
MD039: false # Espaços dentro de texto de link
MD040: false # Blocos de código delimitados devem ter um idioma especificado
MD041: false # First line in file should be a top level header
MD042: false # First line in file should be a top level header
MD043: false # First line in file should be a top level header
MD044: false # First line in file should be a top level header
MD045: false # Code block style
MD046: false # First line in file should be a top level header
MD047: false # File should end with a blank line
MD048: false
MD049: false
MD050: false
MD051: false
MD052: false
MD053: false
MD054: false
MD055: false # Tables: Each row must start and end with a | #464
MD056: false # Tables: Number of columns is the same for all rows #464
MD057: false # Tables: In the second row every column must have at least
MD058: false
